
name: Test nushell setup

on:
  push:
    branches:
      - fix/wf
    paths-ignore:
      - '**.md'
  workflow_dispatch:

# defaults:
#   run:
#     shell: nu {0}

# permissions:
#   id-token: write
#   contents: read

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # https://github.com/marketplace/actions/setup-nu
      - name: set up nushell
        uses: hustcer/setup-nu@develop
        with:
          # Use true to register all plugins
          # enable-plugins: true
          # Or register specified plugins by `,` separated string
          enable-plugins: nu_plugin_inc,nu_plugin_polars,nu_plugin_query
          version: "0.95.0"
      - shell: nu {0}
        run: print (version); print $"(char nl)Dir contents:(char nl)"; ls ((which nu).path.0 | path dirname)
